### PR TITLE
Help branchi

### PR DESCRIPTION
**Pull request by Gyssim**

### CODE REVIEW

**Comment by l-marchesi** [comment]
todo: 
- 14 checkstyle errors
- try to use local page

**Comment by l-marchesi** [comment]
Discussed with UM: We will ask Mr Standtke on what he thinks about it.

**Comment by Gyssim** [comment]
fixed checkstyle errors

**Comment by martinfrancois** [comment]
Any news here from the customer @Gyssim ?

**Comment by Gyssim** [comment]
@martinfrancois changed to local html help file, please approve

**Review by martinfrancois — APPROVED** [review]
Looks good now!

**Pull request merged**
