### PR TITLE
Little design improvments

### PR DESCRIPTION
**Pull request by l-marchesi**
We made some smaller design improvments like button size and styling

### CODE REVIEW

**Comment by martinfrancois** [comment]
Overall, good job!

I tested it on the potato and noticed that the gap in the expert settings on the top is quite large. I tried setting on line 180 the line from: settingsPane.setPadding(new Insets(25)); to: settingsPane.setPadding(new Insets(10, 20, 20, 20)); and now it looks like this:
image
the dialog on the left is with 25 and the one on the right with 10,20,20,20
How does it look in Full HD and 4K, maybe @l-marchesi and @JenniferMue could test it?

Besides that, feel free to merge once that's resolved 😃

**Review by martinfrancois — APPROVED** [review]
see comment before this one

**Comment by martinfrancois** [comment]
I just noticed, the version number seems to be gone here? Maybe you guys could have a look?
EDIT: works now after merging in develop

**Comment by l-marchesi** [comment]
From my side there is nothing to add then - I didn't test it in full HD, but it will be looking good :+1:

**Pull request merged**
