### PR TITLE
can be reset to defaults, Stun servers can be edited

### PR DESCRIPTION
**Pull request by pwigger**
Settings are being reset in the model: user settings are not stored! maybe a task for jan to read and write it from an to the xml

### CODE REVIEW

**Comment by rmosimann** [comment]
I was so free to add "Saving" and "loading" of those user prefs. Still missing the StunServers.

**Comment by rmosimann** [comment]
@pwigger What about limiting to 4 STUN-Servers and make StringProperties and TextFields for them? in the actual form it is not possible to add a new one, but 4 should be enough. What do you think?

**Comment by pwigger** [comment]
kind of looks nicer if you can add unlimited... i adjusted the form and added 2 buttons to add and remove servers. should work that way i think..

**Comment by pwigger** [comment]
btw...Chloe misses some comments in the model  ;)

**Comment by rmosimann** [comment]
Chloe is happy again. And STUNServers are also saved an loaded. 
Proper implementation of loading DEFAULT is still missing.

**Comment by pwigger** [comment]
What do you mean by proper? .. cant we just add readonly Values to the xml file and load those once you click default?

**Comment by rmosimann** [comment]
That sounds good to me.

**Comment by martinfrancois** [comment]
Since there were a lot of things and it would've been too complicated to explain it all, I fixed all of the bugs as I see it. You can now save and load the default settings, as well I implemented that the defaults button doesn't close the dialog and pressing the defaults button will not automatically save the defaults, only if you press "apply".
Since there have been quite a big amount of changes by me, I'd be glad if someone could have a look at it.

**Comment by pwigger** [comment]
Fixed some checkstyle errors. To the load of constants we have now in the model... wouldnt it be nicer if we have those constants in the xml? instead of hardcoded defaultvalues in the code? like a xml kind of <br>
`<settings>`<br>`
<usersettings></usersettings>`<br>`
<defaultsettings></defaultsettings>`<br>`
</settings>`

**Comment by martinfrancois** [comment]
It may be nicer, but would require us to write a new class and port some methods of the supporthelper over so it works with the settings - I think for now it's best to focus on other things, since it works.

**Comment by martinfrancois** [comment]
added TODO for @pwigger's proposal at issue #196

**Pull request merged**
