### PR TITLE
Fix supporters list bug

### PR DESCRIPTION
**Pull request by martinfrancois**
Fixes issue #116  and #109 
- Implemented supporter list in a way that there is always an empty supporter address at the end - which is the + element
- Added logger entry when loading the default list
- Changed implementation of creating a new supporter in a way so clicking on any supporter besides the last button, even if it says "+" will not create a supporter anymore.
- Removed unnecessary TODO
- Added proper saving to XML

### CODE REVIEW

**Comment by rmosimann** [comment]
@martinfrancois Can you tell me where the supporter list is saved? I cannot find it. And I'm not sure if the [+] was there in the beginning.

**Comment by martinfrancois** [comment]
@jpduloch the supporter list is saved in the preferences, those are maintained by java themself, so I don't really know the path. If you want to know what is being saved to the preferences, you could put a sout in "  private void setSupportersInPreferences(String supportersXmlString) {" since this is the method responsible for saving it to the preferences
What do you mean by the + in the beginning?

**Review by rmosimann — APPROVED** [review]
I found it. Seems OK. You have my good to go.

**Comment by martinfrancois** [comment]
Thanks!

**Pull request merged**
